mysql:
  ip: *
  username: *
  password: *
  dbname: *

mongodb:
  ip: *
  port: *
  username: *
  password: *
  dbname: *
  collection: *

corporate:
  id: 38

store:
  corporate_id: 38

mail:
  from: *
  to: *
  bcc: None
  port: 587
  server: smtp.gmail.com
  password: *
  subject: Comparison result bewteen ava and dayoff csv data with mongodb