mysql:
  ip: *
  username: *
  password: *
  dbname: *

mongodb:
  ip: *
  port: *
  username: *
  password: *
  dbname: *
  collection: *

corporate:
  id: *

store:
  corporate_id: *

mail:
  from: *
  to: *
  bcc: None
  port: *
  server: *
  password: *
  subject: *
